### ISSUE TITLE
Different themes per instance

### ISSUE THREAD

**Issue by deadcoder0904** [johnpapa/vscode-peacock#103]
Idk if it's out of the scope of this project but since it automatically writes to `.vscode/settings.json` I thought it might be a good idea to change themes too per instance.

The solution is here - https://github.com/Microsoft/vscode/issues/44268#issuecomment-369518371

Basically it's this -

### WORKSPACE-1

```js
{
    "workbench.colorTheme": "Quiet Light"
}
```

###  WORKSPACE-2

```js
{
    "workbench.colorTheme": "Monokai"
}
```

I personally think it's a good idea & your extension has a good name that will suit it too :)

**Comment by johnpapa** [comment]
that's a fascinating idea. How would this work and affect what's here?

If someone wants to propose a plan for this, I think it could be interesting. (i like design plans)

**Comment by deadcoder0904** [comment]
Just gotta do it like how it shows `Themes` now (press `CMD+K+T` to see). It looks like this -

![VSCode Themes](https://user-images.githubusercontent.com/16436270/54367185-fa02bc00-4697-11e9-8c71-5ea70ad117f5.png)

So it'll be another option like `Peacock - Choose Theme` & then it'll show all Themes which when selected would add it to `.vscode/settings.json` like above.

**Comment by musicfuel** [comment]
I think the issue we will come up with is that the [VS Code API](https://code.visualstudio.com/api/references/vscode-api) is very limited in what it can do with regard to themes. The best way for this to work would be for it to display the installed themes in a quick pick dropdown like above, but I can't see any abilities in the extension API that would allow us to get a list of themes like this.

Without the ability to quick pick we could simply allow the user to enter the theme name in an input box, but at that point we are really only adding a little UI to set the `workbench.colorTheme`. Given the error prone nature of the input I don't think that would be all that valuable.

**Comment by johnpapa** [comment]
Good points @musicfuel . We'd need access to the API for this.

**Comment by deadcoder0904** [comment]
Can't we ask VSCode to provide API for that?

**Comment by musicfuel** [comment]
Yes, but it is all a matter of priority against the roadmap. I suppose someone could contribute support, but I don't know what the process for that is when it comes to adding to the API.

The existing built in list you captured above largely does this already, but it does it for all instances rather than the current. Rather than add this to Peacock, I wonder if a better approach might be to submit an issue or PR to VSCode that provides a new command, something like "Preferences: Color Theme for Current Workspace". The functionality would be nearly the same as the existing "Preferences: Color Theme" command and could use native calls to display the list for selection, but would handle the result to set the workspace setting.

**Comment by deadcoder0904** [comment]
There's an open issue already https://github.com/Microsoft/vscode/issues/44268

**Comment by johnpapa** [comment]
Neat idea - but closing this for now. If a proposal comes through, we can reopen.
