### ISSUE TITLE
Add option to disable creation of `.vscode` directory when opening new window

### ISSUE THREAD

**Issue by dhermes** [johnpapa/vscode-peacock#121]
# Add option to disable creation of `.vscode` directory when opening new window

## Version Information

> macOS 10.14.3 Mojave
> VS Code version: 1.32.3 / a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4 / x64 / stable
> Version of Peacock: `johnpapa.vscode-peacock@2.0.0`

## Repro steps

Not applicable

## The log given by the failure

Not applicable

## Mention any other details that might be useful

I'm happy to send a PR if you're open to it / if you think it'd be straightforward to do.

**Comment by johnpapa** [comment]
Can you help clarify the use case?

**Comment by dhermes** [comment]
I'd like the option of not creating a `.vscode` subdirectory in each of my projects. It's an unexpected side effect, and most of my projects don't have `.vscode` in the `.gitignore`.

**Comment by Calinou** [comment]
@dhermes You can add `.vscode/` to your [global .gitignore file](https://stackoverflow.com/a/22885996/5090885), so that it will always be ignored in all projects. If you still want to commit it to version control in specific repositories, you can use `git add -f .vscode/` to add it explicitly (which will bypass any `.gitignore` file).

**Comment by johnpapa** [comment]
Thanks for the good solution @calinou

I don’t see Peacock making an option to avoid the folder entirely - at least not unless code changes how it works with settings
