### ISSUE TITLE
Darker hues

### ISSUE THREAD

**Issue by Yanpas** [johnpapa/vscode-peacock#158]
My main use of extension is to differentiate folders where I work. Currently most of favourite colors are well suited for light theme, but look too bright on dark themes.

I would like to see hues like from this [extension](https://github.com/stuartcrobinson/unique-window-colors) 

![image](https://user-images.githubusercontent.com/7345761/59351080-422c8b80-8d26-11e9-8896-093ed6305681.png)

**Comment by johnpapa** [comment]
The "surprise me" feature should randomly choose colors. @musicfuel can verify if there are any limits.

Or you can enter a color of a darker hue, if you prefer.

**Comment by Yanpas** [comment]
What do you think if each "Favourite" color will have dark counterpart (e.g. "Angular red light", "Angular red dark")?

"Surprise me" provides mostly bright colors

**Comment by johnpapa** [comment]
I'm hesitant to add a double set of favorites (it is already large).

But I like the idea of darker hues of the same color. Imagine a user chooses surprise me and they like that color, but they want it a little darker shade. We could add a command that darkens the hue. The question becomes "by how much?" No amount would make everyone happy. So do we add a color picker? That's almost too much. I think there is something here ... need to think through some ideas ... but I like it.

**Comment by musicfuel** [comment]
I agree with @johnpapa that a second set of favorites is probably too much. Same for the color picker since if a use wants that level of control a hex entry should suffice.

The Surprise Me feature is truly random and there aren’t any constraints on it from what I recall. I do like the idea of darkening or lightening the current color to alter it. This would pair well with Surprise Me or any of the other features to tweak the color and then maybe use Save To Favorites from there. This gives the user the power to create Angular dark/light if they so choose.

I could see this working either as an increment where you would choose “Darken Current Color” and it would always go 10% darker. Alternatively, we could have the user specify a percentage or a drop down of canned settings like “a little, more, a lot, etc”

Thoughts?

**Comment by johnpapa** [comment]
Yes - the increment is what I was leaning to. Perhaps 'lighten 10%` or `darken 10%`. But also, custom entry. That could be 3 commands. Hmmm. I want it to be easy, but also not make a mess of the menu.

**Comment by johnpapa** [comment]
I have a branch that handles darken and lighten here. Trying this out. https://github.com/johnpapa/vscode-peacock/tree/feature/darken

**Comment by johnpapa** [comment]
here is an example of how it could work

![2019-06-15_12-47-27](https://user-images.githubusercontent.com/1202528/59554082-37633800-8f6c-11e9-9f72-414186822524.gif)

**Comment by johnpapa** [comment]
Closing this issue in favor of PR #180
