### ISSUE TITLE
Reverting to original Peacock colors from Remote

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/vscode-peacock#204]
## Reverting to original Peacock colors from Remote

Some thoughts on entering and leaving remotes. I am interested in what @egamma might have to say on this, as you know more about the Remote API than I do.

One current problem has been the logic to go to Remote, then back to "normal" state. For example, this scenario should work:

1. Your current peacock color is #f00 (stored in workspace settings)
2. You set the Remote Dev Container color to #00f (stored in memento)
3. You open the dev container and the color changes to #00f (now in the workspace settings, we lost the peacock color)
4. You close the container and the color changes to #f00 (where do we get this from?)

The catch is that for this to work it is important to know when you are leaving the Remote experience. Currently there is no event for this. 

Instead, we are checking the remote ENV to see if it is `undefined`. This happens when we leave the remote but also happens additional times (like startup). So its not a true "i left the remote" event.

Also, If it is `undefined` then we change to the Peacock original color. But where can we get the previous color?  Current implementation stores a new memento for the most recent color from Peacock (not from Remote). So here is the revised scenario:

1. Your current peacock color is #f00 (stored in workspace settings AND a memento)
2. You set the Remote Dev Container color to #00f (stored in memento)
3. You open the dev container and the color changes to #00f (now in the workspace settings, we lost the peacock color)
4. You close the container and the color changes to #f00 (from the new memento)

This works - however I introduced a new parameter called `primaryEnvironment` to the `changeColor` function to help with this. When set to `false` the peacockColor memento will not be overwritten. Since `changeColor` is the critical path for changing a color, all logic for changing a color flows through it. Every place that calls it will default to `true` for the `primaryEnvironment`, and where it is called from a place that switches us to use Remote, it explicitly passes `false`. This seems to work in the tests. However it is a bit of a hack, IMO.

Ideally the solution to this would be to have an event for when we enter or leave the Remote.

**Comment by egamma** [comment]
@johnpapa 

>Ideally the solution to this would be to have an event for when we enter or leave the Remote.

Here is what happens when the user transition from a local workspace to a remote workspace:

- User works in a local workspace
  - `vscode.env.remoteName === undefined`
- User executes 'reopen folder in container'
  - the current workspace is closed
  - the peacock extension is deactivated
  - the extension host process is terminated
  - the remote workspace is opened
  - the extension host process is started
  - `vscode.env.remoteName === remote`
  - the peacock extension is activated

From this sequnence you can see that an event would not help. Entering or leaving a remote workspace involves a full restart of the extension host, which terminates and restarts the extension. As a consequence the extension could not react to this event. One option would be to do some clean-up work in the extension's `deactivate` function  when in the remote context and `vscode.env.remoteName` is `!= undefined`.

>Instead, we are checking the remote ENV to see if it is undefined. This happens when we leave the remote but also happens additional times (like startup). So its not a true "i left the remote" event.

The property `vscode.env.remoteName` is constant during an extension host session see the sequence described above.

**Comment by johnpapa** [comment]
this will be fixed in #225
