### ISSUE TITLE
Issue with notification

### ISSUE THREAD

**Issue by cfjedimaster** [johnpapa/vscode-peacock#207]
**Describe the bug**
Sorry for the slightly vague title. On selecting a new project, I get:

```
Peacock changed the base accent colors to [object Object], because the setting is enabled for surpriseMeOnStartup
```

**Comment by johnpapa** [comment]
Are you using the released version 2.4.0 ? Or the 2.5.0-rc? If the latter, can you try the latest on I pushed and report back?

**Comment by cfjedimaster** [comment]
2.5.0-rc. "Try the latest" - you mean go back to the released version?

**Comment by johnpapa** [comment]
I have updated the release since we spoke last week. So it may be helpful to try the release download again.

**Comment by cfjedimaster** [comment]
Release is perfect, so it must just be the 2.5.0 version.

**Comment by johnpapa** [comment]
Let me clarify ... "release" are these https://github.com/johnpapa/vscode-peacock/releases

This is where 2.5.0-rc exists. This has been updated since you first posted your other issue and I recommend you re-download it and try it again. Then report back.

the current published version is 2.4.0.

**Comment by cfjedimaster** [comment]
Confirmed I see it in latest RC.

**Comment by johnpapa** [comment]
Thanks. Can you list the repro steps so that i might follow?

**Comment by cfjedimaster** [comment]
I just opened a new folder. I have the setting to surprise me from favorites.

**Comment by johnpapa** [comment]
here is what i am trying

1. I installed the rc from the "release" link here in github. just now. (using steps on that page)
2. i set "surprise me on startup" to true
3. i choose to "open" from the main menu/
4. i select a folder i have never been to
5. the color changes and this message below is shown

![image](https://user-images.githubusercontent.com/1202528/61488025-3b241900-a975-11e9-81d7-5563bf2d653c.png)


Are you sure you have downloaded the latest rc from releases? Can you try uninstalling your peacock extension and trying the 2.5.0 rc on this page again? https://github.com/johnpapa/vscode-peacock/releases/tag/2.5.0-rc1 I know you did this a week ago, but it has been updated since then (i had an issue with it initially)

**Comment by cfjedimaster** [comment]
I grabbed the VSX download and installed from there for sure. I'll try again though.

**Comment by cfjedimaster** [comment]
On repeat, the same. Using latest Insider. (Forgot to mention that, sorry!)

**Comment by johnpapa** [comment]
ok - are the steps i followed the same as yours? 

I cannot repro this.

**Comment by cfjedimaster** [comment]
One small difference - I also have that option to select from favorites.

**Comment by johnpapa** [comment]
OK, thanks. I tried that too and it seems to be working in the vsix on this page for me and in my tests that check for this. https://github.com/johnpapa/vscode-peacock/releases/tag/2.5.0-rc1

I'll keep it open for a bit and see if anyone else has this issue as I can not reproduce it here.

**Comment by cfjedimaster** [comment]
To be honest I almost wish the notification didn't happen. I know I installed Peacock and why I did it. :)

**Comment by johnpapa** [comment]
i couldnt repro, but i agree that i prefer less notifcations. i moved this message to the logging, where it is available, but not in your face.
