### ISSUE TITLE
Multiple remote workspaces should each be able to have their own color

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/vscode-peacock#224]
## Scenario

You could have multiple vs codes open, all in different remote containers (for example).

People would now use the standard Peacock commands to change colors while they are in a remote. 

## Action Items

1. Remove the remote commands
2. Remote the remote command tests (or refactor)
3. Define default colors for each of the 3 remote settings (in package.json) - addresses #217 
4. Rename the 3 remote settings to say "default"

**Comment by johnpapa** [comment]
One problem we should discuss ...

- local folder is open and peacock is yellow
- you go to a remote container and it chooses the default value (red) 
- you change it to blue
- you go back to the local folder (yellow)
- this works so far
- now go back to remote container. currently it goes back to the default (red) and not the last value you set (blue)

this assumes its ok to not be able to save colors for a specific workspace's env.

if we want it to work otherwise, we either need to save the value to workspace settings or a workspace memento. If we save to workspace settings, we're adding a custom setting to workspace. Not sure we want to do that or if its even a good thing. If we save to memento, the user will never be able to see it, which is not great. So neither of these appeal to me.

Finally ... if the goal is really to have multiple vs code instances open in different containers, and allow each to be a unique color, we have that. But those colors are not saved. You could have this sequence of events:

- local folder is open and peacock is yellow
- you go to a remote container and it chooses the default value (red) 
- you change it to blue
- you open a second vscode instance (vscode2)
- in vscode2, local folder is open and peacock is white
- in vscode2, you go to a remote container and it chooses the default value (red) 
- in vscode2, you change it to green
- you now have a green and blue instance open as desired
- you refresh vscode2 and the color resets to the default remote container color (red) --- is this ok?


If we want the colors to be remembered, we either need to save the colors at a workspace level (memento or workspace setting) as discussed above, or another option is when you change the peacock color while in a remote env for containers, we also change the default remote container color in settings. Is that valuable or expected?

I'd love your feedback on this @egamma

**Comment by egamma** [comment]
The title reads a bit strong 'Each remote workspace should have its own unique color'. To me the feature is: 'A remote workspace should hava a default color that the user can overwrite'.

>Define default colors for each of the 3 remote settings (in package.json) - addresses #217

Since we are on the path to simplify things. I start to think that we should have only a single 'default remote color' and not distinguish on the remote names. There will be other remote contexts than WSL, Containers, and SSH and they should also get a default color out of the box. 

For the color value I suggest that we use the 'remote' color we use for the extension icons (70.116,193)
<img width="104" alt="image" src="https://user-images.githubusercontent.com/172399/61931410-d7a37800-af80-11e9-84fc-345778740ee5.png">

Regarding the sequence:

>- local folder is open and peacock is yellow
>- you go to a remote container and it chooses the default value (red)
>- you change it to blue
>- you go back to the local folder (yellow)
>- this works so far
>- now go back to remote container. currently it goes back to the default (red) and not the last value you set (blue)

This has worked when I was in the state of the PR https://github.com/johnpapa/vscode-peacock/pull/223.

**Comment by johnpapa** [comment]
I agree with your title change. Updated above.

I'm moving my comments for discussions on this topic to the PR for now.

**Comment by johnpapa** [comment]
closing this as default discussions can happen in #217 

and the rest is resolved in #225
