### ISSUE TITLE
[Feature] Add debuggingBackground color

### ISSUE THREAD

**Issue by Jayphen** [johnpapa/vscode-peacock#271]
The extension currently does not modify the background colour of the status bar in debug mode, i.e. `statusBar.debuggingBackground`.

It would be great if this could be added to the object of generated colours, perhaps with a different shade of (or complementary of) the default background.

**Comment by johnpapa** [comment]
Thanks for reporting this. I have had a similar thought ... my theme colors the debugging background for the status bar, so I can imagine others may want their debug background to be either left alone or possibly shaded subtly from their chosen color.

One possibility is to color it the same as the peacock color but with a different shade variation (like the lighten/darken affects). It could be a setting to allow debugging to be colored like peacock with this shade ... or it could just happen by default.

I hesitate before I add new settings because it adds to the surface area of what a user needs to know when using Peacock. I also hesitate to new features that may be off putting to some users, while welcomed by others.

I have to give this some more thought. I welcome further opinions on this.

**Comment by Borongaj** [comment]
It would be really nice if Peacock could update the `statusBar.debuggingBackground` setting too !

**Comment by johnpapa** [comment]
@musicfuel do you have any ideas on how we could come up with a third distinct, visually obvious, color for debugging?

**Comment by musicfuel** [comment]
I would tend to agree that it could be a complementary color of the chose color. A different shade may not be distinct enough or too difficult to distinguish with lighter or darker shades. It isn't too different from what is done already to determine a suitable badge color. Perhaps the same algorithm could be used or serve as inspiration for this. I will try playing around with some concepts here.

**Comment by superandrew** [comment]
I agree with @musicfuel

**Comment by johnpapa** [comment]
@musicfuel - have you had a chance to play with this? I like that idea too

**Comment by musicfuel** [comment]
I haven’t, but I will make time now to take a look and try some ideas.

**Comment by johnpapa** [comment]
thanks again @musicfuel
