### ISSUE TITLE
default faves won't appear in user settings.json until they are modified

### ISSUE THREAD

**Issue by pwahlmueller** [johnpapa/vscode-peacock#354]
**Versions (please complete the following information):**

- OS: Microsoft Windows Server 2016 Standard
- VS Code version 1.42.0
- Peacock Version 3.3.1

**Describe the bug**
When removing the peacock.favoriteColors from settings.json the setting will reappear when starting VSCode again.

**To Reproduce**
1. Remove peacock.favoriteColors from settings.json
2. Save settings.json
3. Close VSCode
4. Reopen VSCode
5. See settings.json

**Expected behavior**
Settings.json without peacock.favoriteColors - this properties only fill up settings.json unneeded.

**Comment by johnpapa** [comment]
Thank you @pwahlmueller for creating this issue!

**Comment by johnpapa** [comment]
Thanks - I see this happening. I'll need to investigate the consequences of doing this, but I agree that if you don't like the favorites that you should be able to remove them.

But ... would you really prefer having zero favorites? If so, why use peacock?

Currentlly, if peacock sees you have an empty array or no setting at all for favorites, it adds the defaults. 

Another option is that I could prompt the user to see if they want to add the favorites back (there is a command for adding them already, but I doubt anyone uses it). Wish I had telemtry on this.

Let me think about this more.

**Comment by pwahlmueller** [comment]
Thanks...
Maybe I'm using peacock the wrong way and I could have an easier solution. But I like the idea, that every Workspace has its own (random) color - I don't prefere any color. 
And I like to have the accent borders in the same color. So that's what I take peacock for.

![grafik](https://user-images.githubusercontent.com/8706955/75097543-37601100-55ac-11ea-972e-78aaac63f87a.png)

**Comment by willpower232** [comment]
FWIW I don't use the favourites either, I use peacock to set the colour of the editor to the main brand colour of whichever website I'm working on so I can easily tell them apart. I've just gotten used to backing up the unused colours :-P

**Comment by pwahlmueller** [comment]
A work around for me is, to define only one favorite color - so the settings.json is smaller.

**Comment by gandalfsaxe** [comment]
@johnpapa Shouldn't the default favorite colors be part of a default config json saved in `~/.vscode/extensions`, and not go into the User`/settings.json` unless explicitely changed? The user `settings.json` would be quite crowded if all extensions threw in it's default settings :)

**Comment by johnpapa** [comment]
Good question @gandalfsaxe . Extensions do save their default settings that are changeable in the user settings.json. The favorites are a starter set which can then be changed by each user (because everyone has different preferences). So the options I considered originally were:

## hard code favorites in the code base
pros: no settings at all
cons: nobody can customize them. and if I allowed custom ones, this would be a mess of code to support.

## no favorites by default

pros: nothing in the user settings
cons: lots of people were very confused at one point when there were none of these. they didnt know how to use peacock. favorites have become the first thing people use.

## limited favorites by default 

currently there are a handful of these. I could remove some more and only keep 3 or 4.

this would be a good compromise, IMO

cons: some people may wonder what happened to them.

**Comment by gandalfsaxe** [comment]
@johnpapa Are you sure? I just have many extensions that don't show anything in `User/settings.json` until I actually change one of it's defaults, then it pops up in `settings.json`.

Take [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker). This is a good example because you can see it has booleans, numbers and lists as default options:
![image](https://user-images.githubusercontent.com/12127864/75477574-d1ed9500-599c-11ea-829d-efeada41a936.png)
Yet despite having these defaults, it contributes nothing to my `User/settings.json` unless I change a default.

To illustrate, I can copy the default setting of "Ignore Paths" (`cSpell.ignorePaths`) as JSON:
![image](https://user-images.githubusercontent.com/12127864/75477735-0d885f00-599d-11ea-95fe-28f0bbe975aa.png)
which on the clipboards is:
```
"cSpell.ignorePaths": [
  "**/package-lock.json",
  "**/node_modules/**",
  "**/vscode-extension/**",
  "**/.git/objects/**",
  ".vscode"
]
```

I'm thinking the same should be doable for Peacock?

**Comment by johnpapa** [comment]
Yes. You can have defaults defined and only when changes will they appear in settings. That might be a possibility. But as soon as you add, change or remove any favorite the entire array would appear on your settings because Code treats the entire array as one setting. 

What do you think of that?

**Comment by gandalfsaxe** [comment]
Yes I think that's a win-win. The users who don't care to customize the favorites will never see it in their user settings, and the people who do want to customize won't care too much that the full list is there.

In addition to this, yes reducing the number of default colors could probably make sense. It's hard to quickly visually distinguish that many colors anyway. 3-4 might be too few, probably somewhere around 6-10 would be better than 14.

The deluxe solution would be a numberOfColors variable. The favorite colors could then be as different as possible for any N numbers up to 10 or 14 or so.

**Comment by gandalfsaxe** [comment]
But that could be too much work for little gain, I think just having the defaults only appear when changes are made would be fine for now, at least for me 😊

**Comment by johnpapa** [comment]
I think I like to separate these into two issues:

1. reduce favorites
2. default faves won't appear in user settings.json until they are modified

I just renamed this issue for 2

Opened a new issue for 1 at #358

**Comment by johnpapa** [comment]
Thanks for the feedback. I think these are excellent additions (actually reductions) to Peacock.
