### ISSUE TITLE
Don't reset the color scheme every time Code opens

### ISSUE THREAD

**Issue by STGHMAAV** [johnpapa/vscode-peacock#355]
Hi!

I use Peacock a lot so I don't get confused about on which solution I'm coding and the extension is really useful for that. I tried to manually change "statusBar.background" to a different color on settings.json so every branch of the project is color-coded on the statusBar where on Code it actually says on which branch you're on. The thing is, every time I close and reopen Code, that change resets to the default color that was selected to be the general color.  So the request is for that, allow to make custom palettes and don't reset them every time Code reopens.

**Comment by johnpapa** [comment]
Thank you @STGHMAAV for creating this issue!

**Comment by johnpapa** [comment]
I see your point on this.The reason this happens is that peacock has to respond to many events and adjust the colors based upon those. It always defers back to what the `peacock.color` is. So if you adjust a color, it hears that event, and looks for that setting. That's why this happens to you. If we remove this event listening it would break a lot of functionality (i've tried in regression testing).

I'm not sure how this could be done.

If you want to adjust the colors, I recommend setting using the "enter a color" menu option or using the lighten and darken features
