### ISSUE TITLE
[Feature Request] Allow saving of color options instead of peacock.remoteColor

### ISSUE THREAD

**Issue by hyoretsu** [johnpapa/vscode-peacock#448]
**Is your feature request related to a problem? Please describe.**
To put it simply, the theme Peacock offered when I entered a color was too bright. So I tweaked a few colors here and there, but Peacock only saves the default colors for the hex code I first entered.

**Describe the solution you'd like**
Save the `workbench.colorCustomizations` instead of `peacock.remoteColor`

**Additional context**
![Original theme](https://user-images.githubusercontent.com/20804322/120253473-cfdc4b00-c25d-11eb-8359-a5982b92e00f.png)
Original theme

![image](https://user-images.githubusercontent.com/20804322/120253540-02864380-c25e-11eb-962a-2e0f8db9e93b.png)
After some tweaks to colors

![image](https://user-images.githubusercontent.com/20804322/120253703-77f21400-c25e-11eb-8b8c-816947f06e2c.png)
Changing `peacock.remoteColor` to something closer to what I want also doesn't quite work

**Comment by johnpapa** [comment]
Thank you @hyoretsu for creating this issue!

**Comment by willpower232** [comment]
If you remove `"peacock.remoteColor"` and make your changes to the customizations then close and reopen the workspace, does Peacock leave it alone or does it make another change in a slightly different way?

**Comment by hyoretsu** [comment]
@willpower232 Peacock doesn't change it because there are no options associated with it turned on, but then it's the same as not using Peacock and changing the colors manually. All it did in that case was suggest some base colors.

**Comment by johnpapa** [comment]
Hi. Peacock works by using then menu system and commands. If you find a color you like you can choose "enter color" from the command palette and it will set it. 

If you find you want to tune it more you can use the lighten and darken commands. 

If you decide to modify the colors directly in settings you could do that and uninstall peacock as it would not be needed.

**Comment by hyoretsu** [comment]
So Peacock allows an uncustomizable customization. Would still be great if it "expanded" to be a sort of theme manager. Since, y'know. It's pretty much what it is, except that we're stuck with the colors it sets for us.

**Comment by MetaMmodern** [comment]
@johnpapa hello! Thank you for everything you've done for the developers community over the years!
The previous comment about customization without customization also affects me. I'm working on a frontend project and designers have a theme for frontend so I thought I't sgonna be fun to have that same color scheme in vscode as well. But when I started editing colors in settings.json I noticed that changing peacock.color changes my overriden colors(which is alright as I understood from other issues). So I was hoping that I could create a color "theme" and save it into peacocks memory so that I could select it later. However, adding color to favorite colors makes peacock recalculate all values and override what I've set.

I know it's kinda not even on a roadmap, but do you maybe think that would be a great addition to next major release? To save the complete theme. Or do you think that it's better to have it as a vscode theme instead?
