### ISSUE TITLE
Allow choosing a color from another location

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/vscode-peacock#8]
package.json?

editorconfig?

is this even desired?

**Comment by burkeholland** [comment]
Or perhaps just the settings file? Make it a setting and people can check into source so anyone using VS Code gets it?

I don't know if it's canonical to check .vscode folders into source

**Comment by johnpapa** [comment]
it's int he settings now (workspace)

**Comment by johnpapa** [comment]
closing this as settings seems logical, as Burke suggests

**Comment by jamiebarrow** [comment]
@johnpapa I work as a developer on teams where perhaps my own preferences may differ to those of the teams. Because of this, I wondered if Peacock has the ability to setup settings for specific repos I have checked out, without actually saving these settings to the repo.

Linking my own preferences, to the preferences of the workspace somehow.

I'm not sure if there's a way to for example store in my own user preferences, a "peacock.color" per repo / project, so that if I open a project in my own machine, the settings are applied to that project, but then not persisted in the team's shared configuration.

Then if the team itself doesn't even want to use Peacock at all, but I do, it also enables me to have a nicer experience for myself. Or if maybe the team does use Peacock, but I prefer a darker colour to a more bright colour on certain projects, so that they stand out more for me, then it would be great.

I looked for issues but only came across this one, and I do see its older, and closed, so maybe there's not much of a need for it. But thought I'd just add a comment in any case :)

Thanks for the great extension.
